package com.example.smartinventory.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

import com.example.smartinventory.model.PurchaseOrder;
import com.example.smartinventory.model.PurchaseOrderStatus;
import com.example.smartinventory.model.Warehouse;

import io.swagger.v3.oas.annotations.media.Schema;

/** A purchase order raised against a supplier, with its line items. */
@Schema(description = "A purchase order and its line items")
public record PurchaseOrderResponse(

        @Schema(description = "Identifier of the purchase order", example = "4")
        Long id,

        @Schema(description = "Identifier of the supplier the order is raised against", example = "2")
        Long supplierId,

        @Schema(description = "Supplier name", example = "Acme Supplies")
        String supplierName,

        @Schema(description = "Identifier of the warehouse the goods are to be delivered to, or null when the "
                + "order names none", example = "1")
        Long warehouseId,

        @Schema(description = "Code of the warehouse the goods are to be delivered to, or null when the order "
                + "names none", example = "WH-NORTH")
        String warehouseCode,

        @Schema(description = "Lifecycle status of the order", example = "DRAFT")
        PurchaseOrderStatus status,

        @Schema(description = "Free-text note recorded with the order", example = "Quarterly restock")
        String note,

        @Schema(description = "Whether the order was raised automatically by the reorder rule", example = "false")
        boolean autoGenerated,

        @Schema(description = "Ordered line items")
        List<PurchaseOrderItemResponse> items,

        @Schema(description = "Sum of every line total", example = "237.50")
        BigDecimal total,

        @Schema(description = "When the order was created")
        Instant createdAt,

        @Schema(description = "When the order was last updated")
        Instant updatedAt) {

    /**
     * Flattens a persisted order into its response form.
     *
     * @param order the order to convert; its supplier, delivery warehouse, items and their products
     *              must be loadable
     * @return the response payload
     */
    public static PurchaseOrderResponse from(PurchaseOrder order) {
        Warehouse warehouse = order.getWarehouse();
        return new PurchaseOrderResponse(
                order.getId(),
                order.getSupplier().getId(),
                order.getSupplier().getName(),
                warehouse == null ? null : warehouse.getId(),
                warehouse == null ? null : warehouse.getCode(),
                order.getStatus(),
                order.getNote(),
                order.isAutoGenerated(),
                order.getItems().stream().map(PurchaseOrderItemResponse::from).toList(),
                order.getTotal(),
                order.getCreatedAt(),
                order.getUpdatedAt());
    }

}
