package com.example.smartinventory.model;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.annotations.TenantId;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** JPA entity representing a purchase order raised against a {@link Supplier}. */
@Entity
@Table(name = "purchase_orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PurchaseOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Owning tenant; Hibernate stamps it on insert and filters every query by it. */
    @TenantId
    @Column(name = "tenant_id", nullable = false, updatable = false, length = 64)
    private String tenantId;

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id", nullable = false)
    private Supplier supplier;

    /**
     * Where the order is to be delivered, or {@code null} when it is to be booked against the
     * product total only. A receipt against the order lands here unless it names somewhere else.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "warehouse_id")
    private Warehouse warehouse;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private PurchaseOrderStatus status = PurchaseOrderStatus.DRAFT;

    /**
     * When the goods are expected to arrive, or {@code null} when nothing is known about it. Named
     * by the buyer when the order is raised, or worked out from the supplier's lead time when the
     * order is placed; an order placed with a supplier who names no lead time keeps none.
     */
    @Column(name = "expected_delivery_date")
    private LocalDate expectedDeliveryDate;

    /**
     * The day the last of the goods arrived, or {@code null} while any of them are still to come.
     * Stamped when a receipt completes the order, and a record of what happened rather than a figure
     * worked out from anything: an order cannot leave {@code RECEIVED}, and the day its goods landed
     * does not change afterwards the way its lateness does.
     */
    @Column(name = "delivered_date")
    private LocalDate deliveredDate;

    @Size(max = 1000)
    @Column(length = 1000)
    private String note;

    /** Whether the order was raised by the automatic reorder rather than entered by hand. */
    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private boolean autoGenerated = false;

    @OneToMany(mappedBy = "purchaseOrder", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<PurchaseOrderItem> items = new ArrayList<>();

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Adds a line item to this order and sets its back-reference.
     *
     * @param item the line item to attach
     */
    public void addItem(PurchaseOrderItem item) {
        item.setPurchaseOrder(this);
        items.add(item);
    }

    /**
     * Computes the total cost of the order as the sum of {@code quantity * unitPrice}
     * across every line item.
     *
     * @return the order total
     */
    public BigDecimal getTotal() {
        return items.stream()
                .map(item -> item.getUnitPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /**
     * Reports whether the goods were due before the given day and are still being waited on.
     *
     * <p>Lateness is a fact about the day it is asked on rather than about the order: an order due
     * on the eighth is fine on the seventh and late on the ninth, having done nothing in between.
     * So it is worked out when the order is read and never stored.
     *
     * <p>An order due on the given day is not late on it — a delivery has the whole of the day it
     * was promised for — and one carrying no expected delivery date is never late, because nobody
     * promised a day for it to miss.
     *
     * @param on the day to judge the order against
     * @return {@code true} when goods are still expected against it and were due before that day
     */
    public boolean isOverdueOn(LocalDate on) {
        return expectedDeliveryDate != null && status != null && status.isAwaitingDelivery()
                && expectedDeliveryDate.isBefore(on);
    }

    /**
     * Reports how the delivery went against what was promised: whole days between the day the goods
     * were due and the day they arrived. Positive is late, zero is the day promised, and negative is
     * early — an early delivery is information, and reporting it as no days late would throw it away.
     *
     * <p>An order missing either date is not judged at all rather than judged as on time: one still
     * awaiting delivery has no arrival, one placed against a supplier naming no lead time was
     * promised nothing, and one received before arrivals were recorded has nothing to compare.
     *
     * @return days between the promise and the arrival, or {@code null} when the order carries
     *         fewer than both dates
     */
    public Long getDaysLate() {
        if (expectedDeliveryDate == null || deliveredDate == null) {
            return null;
        }
        return ChronoUnit.DAYS.between(expectedDeliveryDate, deliveredDate);
    }

    /**
     * Reports whether every line has arrived in full.
     *
     * @return {@code true} when no line has anything outstanding
     */
    public boolean isFullyReceived() {
        return items.stream().allMatch(PurchaseOrderItem::isFullyReceived);
    }

    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
        if (status == null) {
            status = PurchaseOrderStatus.DRAFT;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }

}
