package com.example.smartinventory.service;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.example.smartinventory.model.Product;
import com.example.smartinventory.model.PurchaseOrder;
import com.example.smartinventory.model.PurchaseOrderItem;
import com.example.smartinventory.model.PurchaseOrderStatus;
import com.example.smartinventory.model.StockLevel;
import com.example.smartinventory.model.Supplier;
import com.example.smartinventory.model.Warehouse;
import com.example.smartinventory.repository.PurchaseOrderRepository;
import com.example.smartinventory.repository.StockLevelRepository;
import com.example.smartinventory.repository.StockReservationRepository;

@ExtendWith(MockitoExtension.class)
class AutoReorderServiceTest {

    private static final List<PurchaseOrderStatus> OPEN_STATUSES = List.of(
            PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.PLACED, PurchaseOrderStatus.PARTIALLY_RECEIVED);

    private static final Warehouse NORTH = Warehouse.builder().id(3L).code("WH-NORTH").build();

    @Mock
    private PurchaseOrderRepository purchaseOrderRepository;

    @Mock
    private StockLevelRepository stockLevelRepository;

    @Mock
    private StockReservationRepository stockReservationRepository;

    /**
     * The real measurer over a mocked reservation store, which holds nothing until a test says
     * otherwise -- so a case that is not about reservations measures the stock on the shelf.
     */
    private AvailableStockService availableStock() {
        return new AvailableStockService(stockReservationRepository);
    }

    private AutoReorderService enabledService() {
        return new AutoReorderService(purchaseOrderRepository, stockLevelRepository, availableStock(), true);
    }

    private Product lowStockProduct() {
        return Product.builder()
                .id(1L)
                .quantity(3)
                .reorderThreshold(10)
                .price(new BigDecimal("2.50"))
                .supplier(Supplier.builder().id(7L).name("Acme Supplies").build())
                .build();
    }

    /** Puts {@code outstanding} units of the product on open orders, wherever they are headed. */
    private void expectOnOrder(int outstanding) {
        when(purchaseOrderRepository.sumOutstandingForProduct(OPEN_STATUSES, 1L)).thenReturn((long) outstanding);
    }

    /** Puts {@code outstanding} units of the product on open orders headed for one warehouse. */
    private void expectOnOrderFor(Warehouse warehouse, int outstanding) {
        when(purchaseOrderRepository.sumOutstandingForProductInWarehouse(OPEN_STATUSES, warehouse.getId(), 1L))
                .thenReturn((long) outstanding);
    }

    private void expectNothingOnOrder() {
        expectOnOrder(0);
    }

    private void expectNothingOnOrderFor(Warehouse warehouse) {
        expectOnOrderFor(warehouse, 0);
    }

    private void expectSavedOrder() {
        when(purchaseOrderRepository.save(any(PurchaseOrder.class))).thenAnswer(inv -> inv.getArgument(0));
    }

    /**
     * Puts a level in the warehouse the movement went through, holding {@code quantity} units under
     * a reorder point of its own.
     */
    private void expectLevel(Product product, Warehouse warehouse, int quantity, Integer threshold) {
        when(stockLevelRepository.findByProductIdAndWarehouseId(product.getId(), warehouse.getId()))
                .thenReturn(Optional.of(StockLevel.builder()
                        .product(product)
                        .warehouse(warehouse)
                        .quantity(quantity)
                        .reorderThreshold(threshold)
                        .build()));
    }

    @Test
    void raisesADraftOrderForTheSupplierWhenStockIsAtOrBelowTheThreshold() {
        Product product = lowStockProduct();
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order).isNotNull();
        assertThat(order.getStatus()).isEqualTo(PurchaseOrderStatus.DRAFT);
        assertThat(order.isAutoGenerated()).isTrue();
        assertThat(order.getSupplier()).isSameAs(product.getSupplier());
        assertThat(order.getNote()).contains("3 units free", "reorder threshold 10");
        assertThat(order.getItems()).hasSize(1);
        PurchaseOrderItem item = order.getItems().get(0);
        assertThat(item.getProduct()).isSameAs(product);
        assertThat(item.getUnitPrice()).isEqualByComparingTo("2.50");
        assertThat(item.getPurchaseOrder()).isSameAs(order);
    }

    @Test
    void deliversTheRaisedOrderWhereTheSupplierDelivers() {
        Warehouse defaultWarehouse = Warehouse.builder().id(2L).code("WH-SOUTH").build();
        Product product = lowStockProduct();
        product.getSupplier().setDefaultWarehouse(defaultWarehouse);
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order.getWarehouse()).isSameAs(defaultWarehouse);
    }

    @Test
    void raisesAnOrderWithNoWarehouseWhenTheSupplierHasNoDefault() {
        Product product = lowStockProduct();
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order.getWarehouse()).isNull();
    }

    @Test
    void ordersTheConfiguredReorderQuantityWhenTheProductSetsOne() {
        Product product = lowStockProduct();
        product.setReorderQuantity(50);
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(50);
    }

    @Test
    void otherwiseOrdersEnoughToReachTwiceTheThreshold() {
        Product product = lowStockProduct();
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(17);
    }

    @Test
    void ordersAtLeastOneUnitWhenTheThresholdLeavesNothingToTopUp() {
        Product product = lowStockProduct();
        product.setQuantity(0);
        product.setReorderThreshold(0);
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(1);
    }

    @Test
    void raisesNothingWhenStockIsAboveTheThreshold() {
        Product product = lowStockProduct();
        product.setQuantity(11);

        assertThat(enabledService().evaluate(product)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingWhenTheProductHasNoSupplier() {
        Product product = lowStockProduct();
        product.setSupplier(null);

        assertThat(enabledService().evaluate(product)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingWhenWhatIsOnOrderCoversTheShortfall() {
        Product product = lowStockProduct();
        expectOnOrder(8);

        assertThat(enabledService().evaluate(product)).isNull();

        verify(purchaseOrderRepository, never()).save(any(PurchaseOrder.class));
    }

    @Test
    void ordersTheDifferenceWhenWhatIsOnOrderDoesNotCoverTheShortfall() {
        Product product = lowStockProduct();
        expectOnOrder(5);
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order).isNotNull();
        assertThat(order.getNote()).contains("3 units free", "5 on order", "reorder threshold 10");
        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(12);
    }

    @Test
    void ordersTheConfiguredQuantityInFullWhateverIsOnItsWay() {
        Product product = lowStockProduct();
        product.setReorderQuantity(50);
        expectOnOrder(5);
        expectSavedOrder();

        assertThat(enabledService().evaluate(product).getItems().get(0).getQuantity()).isEqualTo(50);
    }

    @Test
    void raisesNothingWhenTheProductHasNoThresholdToBreach() {
        Product product = lowStockProduct();
        product.setReorderThreshold(null);

        assertThat(enabledService().evaluate(product)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingWhenTheRuleIsDisabled() {
        AutoReorderService disabled = new AutoReorderService(
                purchaseOrderRepository, stockLevelRepository, availableStock(), false);

        assertThat(disabled.evaluate(lowStockProduct())).isNull();

        verifyNoInteractions(purchaseOrderRepository);
        verifyNoInteractions(stockLevelRepository);
    }

    @Test
    void onlyConsidersUnreceivedOrdersAsCoveringTheShortfall() {
        Product product = lowStockProduct();
        expectNothingOnOrder();
        expectSavedOrder();

        enabledService().evaluate(product);

        verify(purchaseOrderRepository).sumOutstandingForProduct(
                eq(List.of(PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.PLACED,
                        PurchaseOrderStatus.PARTIALLY_RECEIVED)), anyLong());
    }

    @Test
    void ordersForTheSiteThatIsShortWhenItHoldsAReorderPointOfItsOwn() {
        Product product = lowStockProduct();
        product.setQuantity(40);
        expectLevel(product, NORTH, 2, 6);
        expectNothingOnOrderFor(NORTH);
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product, NORTH);

        assertThat(order).isNotNull();
        assertThat(order.getWarehouse()).isSameAs(NORTH);
        assertThat(order.getNote()).contains("2 units free", "WH-NORTH", "reorder threshold 6");
        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(10);
    }

    @Test
    void deliversTheSitesOrderToItRatherThanWhereTheSupplierUsuallyDelivers() {
        Product product = lowStockProduct();
        product.getSupplier().setDefaultWarehouse(Warehouse.builder().id(2L).code("WH-SOUTH").build());
        expectLevel(product, NORTH, 2, 6);
        expectNothingOnOrderFor(NORTH);
        expectSavedOrder();

        assertThat(enabledService().evaluate(product, NORTH).getWarehouse()).isSameAs(NORTH);
    }

    @Test
    void ordersTheConfiguredQuantityForASiteThatSetsNoneOfItsOwn() {
        Product product = lowStockProduct();
        product.setReorderQuantity(50);
        expectLevel(product, NORTH, 2, 6);
        expectNothingOnOrderFor(NORTH);
        expectSavedOrder();

        assertThat(enabledService().evaluate(product, NORTH).getItems().get(0).getQuantity()).isEqualTo(50);
    }

    @Test
    void raisesNothingForASiteThatIsAboveItsOwnThresholdEvenWhenTheProductTotalIsBelowItsOwn() {
        Product product = lowStockProduct();
        expectLevel(product, NORTH, 3, 2);

        assertThat(enabledService().evaluate(product, NORTH)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingWhenWhatIsOnItsWayToThatSiteCoversIt() {
        Product product = lowStockProduct();
        expectLevel(product, NORTH, 2, 6);
        expectOnOrderFor(NORTH, 5);

        assertThat(enabledService().evaluate(product, NORTH)).isNull();

        verify(purchaseOrderRepository, never()).save(any(PurchaseOrder.class));
    }

    @Test
    void ordersTheDifferenceForASiteWhatIsOnItsWayDoesNotCover() {
        Product product = lowStockProduct();
        product.setQuantity(40);
        expectLevel(product, NORTH, 2, 6);
        expectOnOrderFor(NORTH, 1);
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product, NORTH);

        assertThat(order.getNote()).contains("2 units free in WH-NORTH", "1 on order");
        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(9);
    }

    @Test
    void countsOnlyWhatIsHeadedForTheSiteAsCoverForIt() {
        Product product = lowStockProduct();
        product.setQuantity(40);
        expectLevel(product, NORTH, 2, 6);
        expectNothingOnOrderFor(NORTH);
        expectSavedOrder();

        assertThat(enabledService().evaluate(product, NORTH)).isNotNull();

        verify(purchaseOrderRepository, never()).sumOutstandingForProduct(any(), any());
    }

    @Test
    void measuresTheProductTotalWhenTheSiteHoldsNoReorderPoint() {
        Product product = lowStockProduct();
        expectLevel(product, NORTH, 40, null);
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product, NORTH);

        assertThat(order.getNote()).contains("3 units free").doesNotContain("WH-NORTH");
        assertThat(order.getWarehouse()).isNull();
    }

    @Test
    void measuresTheProductTotalWhenTheProductHasNeverBeenStockedThere() {
        Product product = lowStockProduct();
        when(stockLevelRepository.findByProductIdAndWarehouseId(1L, 3L)).thenReturn(Optional.empty());
        expectNothingOnOrder();
        expectSavedOrder();

        assertThat(enabledService().evaluate(product, NORTH)).isNotNull();
    }

    @Test
    void ordersForASiteLeftShortByStockThatOnlyChangedLocation() {
        Product product = lowStockProduct();
        product.setQuantity(40);
        expectLevel(product, NORTH, 2, 6);
        expectNothingOnOrderFor(NORTH);
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluateRelocation(product, NORTH);

        assertThat(order).isNotNull();
        assertThat(order.getWarehouse()).isSameAs(NORTH);
        assertThat(order.getNote()).contains("2 units free", "WH-NORTH", "reorder threshold 6");
        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(10);
    }

    @Test
    void raisesNothingForRelocatedStockWhenTheSiteIsStillAboveItsOwnThreshold() {
        Product product = lowStockProduct();
        expectLevel(product, NORTH, 3, 2);

        assertThat(enabledService().evaluateRelocation(product, NORTH)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingForRelocatedStockWhenWhatIsOnItsWayToThatSiteCoversIt() {
        Product product = lowStockProduct();
        expectLevel(product, NORTH, 2, 6);
        expectOnOrderFor(NORTH, 5);

        assertThat(enabledService().evaluateRelocation(product, NORTH)).isNull();

        verify(purchaseOrderRepository, never()).save(any(PurchaseOrder.class));
    }

    @Test
    void neverMeasuresTheProductTotalForStockThatOnlyChangedLocation() {
        Product product = lowStockProduct();
        expectLevel(product, NORTH, 40, null);

        assertThat(enabledService().evaluateRelocation(product, NORTH)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingForRelocatedStockWhenTheProductHasNeverBeenStockedThere() {
        Product product = lowStockProduct();
        when(stockLevelRepository.findByProductIdAndWarehouseId(1L, 3L)).thenReturn(Optional.empty());

        assertThat(enabledService().evaluateRelocation(product, NORTH)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
    }

    @Test
    void raisesNothingForRelocatedStockWhenTheRuleIsDisabled() {
        AutoReorderService disabled = new AutoReorderService(
                purchaseOrderRepository, stockLevelRepository, availableStock(), false);

        assertThat(disabled.evaluateRelocation(lowStockProduct(), NORTH)).isNull();

        verifyNoInteractions(purchaseOrderRepository);
        verifyNoInteractions(stockLevelRepository);
    }

    @Test
    void ordersOnWhatIsFreeRatherThanOnWhatIsOnTheShelf() {
        Product product = lowStockProduct();
        product.setQuantity(40);
        when(stockReservationRepository.sumHeldForProduct(eq(1L), any(Instant.class))).thenReturn(38L);
        expectNothingOnOrder();
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product);

        assertThat(order).isNotNull();
        assertThat(order.getNote()).contains("2 units free", "reorder threshold 10");
        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(18);
    }

    @Test
    void raisesNothingWhenTheHoldsLeaveEnoughFree() {
        Product product = lowStockProduct();
        product.setQuantity(40);
        when(stockReservationRepository.sumHeldForProduct(eq(1L), any(Instant.class))).thenReturn(5L);

        assertThat(enabledService().evaluate(product)).isNull();

        verify(purchaseOrderRepository, never()).save(any(PurchaseOrder.class));
    }

    @Test
    void ordersForASitePromisedAwayOnTheHoldsPlacedAgainstThatSite() {
        Product product = lowStockProduct();
        product.setQuantity(400);
        expectLevel(product, NORTH, 10, 6);
        when(stockReservationRepository.sumHeldForProductInWarehouse(eq(1L), eq(NORTH.getId()), any(Instant.class)))
                .thenReturn(9L);
        expectNothingOnOrderFor(NORTH);
        expectSavedOrder();

        PurchaseOrder order = enabledService().evaluate(product, NORTH);

        assertThat(order).isNotNull();
        assertThat(order.getWarehouse()).isSameAs(NORTH);
        assertThat(order.getNote()).contains("1 units free", "WH-NORTH", "reorder threshold 6");
        assertThat(order.getItems().get(0).getQuantity()).isEqualTo(11);
    }

}
