blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/monssefbaakka/smart-inventory-management-system/discussions
    about: Ask questions and discuss the project here.
