package com.example.smartinventory.service;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.example.smartinventory.model.Product;
import com.example.smartinventory.model.PurchaseOrder;
import com.example.smartinventory.model.PurchaseOrderItem;
import com.example.smartinventory.model.PurchaseOrderStatus;
import com.example.smartinventory.model.Supplier;
import com.example.smartinventory.repository.PurchaseOrderRepository;

/**
 * Closes the loop between a low stock level and its replenishment: when a product falls to or
 * below its reorder threshold, a {@code DRAFT} purchase order is raised against its supplier so a
 * buyer only has to review and place it.
 *
 * <p>The rule is opt-in through {@code auto-reorder.enabled} and deliberately conservative. It
 * raises nothing for a product with no supplier, and nothing for a product that already sits on an
 * open order, so a shortfall that takes several movements to develop still results in one order.
 */
@Service
@Transactional
public class AutoReorderService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AutoReorderService.class);

    /**
     * Orders that have not yet been received in full, and therefore already cover the shortfall. A
     * part-delivered order counts: the rest of it is still on its way, so a short delivery that
     * leaves the product below its threshold must not raise a second order for the same goods.
     */
    private static final List<PurchaseOrderStatus> OPEN_STATUSES = List.of(
            PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.PLACED, PurchaseOrderStatus.PARTIALLY_RECEIVED);

    /** Multiple of the reorder threshold a replenishment tops stock up to, absent an explicit quantity. */
    private static final int DEFAULT_TARGET_MULTIPLIER = 2;

    private final PurchaseOrderRepository purchaseOrderRepository;
    private final boolean enabled;

    /**
     * Creates the reorder rule.
     *
     * @param purchaseOrderRepository store the raised orders are written to and checked against
     * @param enabled                 whether stock movements may raise orders at all
     */
    public AutoReorderService(PurchaseOrderRepository purchaseOrderRepository,
            @Value("${auto-reorder.enabled:false}") boolean enabled) {
        this.purchaseOrderRepository = purchaseOrderRepository;
        this.enabled = enabled;
    }

    /**
     * Raises a draft purchase order for the product when its stock has reached the reorder
     * threshold and nothing is on order for it yet.
     *
     * <p>Called from within the stock movement transaction, so a failure to raise the order rolls
     * the movement back with it rather than leaving an order for stock that never moved.
     *
     * <p>The order is delivered where the supplier's goods normally go. Nobody is present to name a
     * destination when a movement raises an order, so without that the replenishment would arrive
     * against the product total only — invisible to the location that ran short in the first place.
     *
     * @param product the product whose stock level was just changed
     * @return the raised order, or {@code null} when the rule declined to raise one
     */
    public PurchaseOrder evaluate(Product product) {
        if (!enabled || !needsReplenishment(product)) {
            return null;
        }

        Supplier supplier = product.getSupplier();
        if (supplier == null) {
            LOGGER.warn("Product {} is at or below its reorder threshold but has no supplier to order from",
                    product.getId());
            return null;
        }

        if (purchaseOrderRepository.existsByStatusInAndItemsProductId(OPEN_STATUSES, product.getId())) {
            LOGGER.debug("Product {} is already on an open purchase order; not reordering", product.getId());
            return null;
        }

        int quantity = replenishmentQuantity(product);
        PurchaseOrder order = PurchaseOrder.builder()
                .supplier(supplier)
                .warehouse(supplier.getDefaultWarehouse())
                .status(PurchaseOrderStatus.DRAFT)
                .autoGenerated(true)
                .note("Automatic reorder: stock " + product.getQuantity() + " at or below reorder threshold "
                        + product.getReorderThreshold())
                .build();
        order.addItem(PurchaseOrderItem.builder()
                .product(product)
                .quantity(quantity)
                .unitPrice(product.getPrice())
                .build());

        PurchaseOrder saved = purchaseOrderRepository.save(order);
        LOGGER.info("Raised automatic purchase order {} for {} units of product {} from supplier {}",
                saved.getId(), quantity, product.getId(), supplier.getId());
        return saved;
    }

    private boolean needsReplenishment(Product product) {
        Integer quantity = product.getQuantity();
        Integer threshold = product.getReorderThreshold();
        return quantity != null && threshold != null && quantity <= threshold;
    }

    /**
     * Determines how much to order: the quantity configured on the product, or else enough to
     * bring stock back to twice the reorder threshold. A product whose threshold is zero, or whose
     * stock somehow already exceeds that target, still orders a single unit rather than an empty
     * line.
     *
     * @param product the product being replenished
     * @return the number of units to put on the order, always at least one
     */
    private int replenishmentQuantity(Product product) {
        Integer configured = product.getReorderQuantity();
        if (configured != null) {
            return configured;
        }
        int target = product.getReorderThreshold() * DEFAULT_TARGET_MULTIPLIER;
        return Math.max(target - product.getQuantity(), 1);
    }

}
